In [2]:
import numpy as np

In [3]:
np.zeros((0,2,4))

array([], shape=(0, 2, 4), dtype=float64)

In [4]:
a=np.arange(36*6).reshape((6,6,6))

In [5]:
a

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35]],

       [[ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107]],

       [[108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148

In [7]:
b=a[0:,0:,2]`

In [13]:
b[0:,0]

array([  2,  38,  74, 110, 146, 182])

In [14]:
b.reshape(36)


array([  2,   8,  14,  20,  26,  32,  38,  44,  50,  56,  62,  68,  74,
        80,  86,  92,  98, 104, 110, 116, 122, 128, 134, 140, 146, 152,
       158, 164, 170, 176, 182, 188, 194, 200, 206, 212])

In [22]:
v= list(b[0:10])

In [20]:
b.shape

(6, 6)

In [24]:
type(v[0])

numpy.ndarray